# Generated by Django 2.2.7 on 2019-11-19 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_uuid', models.CharField(default=uuid.UUID('36b15ff1-74d0-4ce0-aaec-20ae0976cfce'), max_length=36, primary_key=True, serialize=False)),
                ('branch_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('base_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('customer_since', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('crd', 'CREDIT'), ('chk', 'CHECKING'), ('svg', 'SAVINGS')], max_length=3)),
                ('product_description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('crd', 'CREDIT'), ('chk', 'CHECKING'), ('svg', 'SAVINGS')], max_length=3)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='bank.Customer')),
            ],
        ),
    ]
